version: '3.4'

services:
  hermes.webapi.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  hermes.worker.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8888"

  hermes.messagequeue.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8087
      - DEPLOYMENT_PORT=${DEPLOYMENT_PORT}
    ports:
      - "8087:2525"