name: Hermes.Infrastructure (.NET Core)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/Hermes.Infrastructure
    - name: Build
      run: dotnet build src/Hermes.Infrastructure --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/Hermes.Infrastructure.Tests --no-restore --verbosity normal
