name: Hermes.Abstrations (.NET Core)
env:
  proj_folder: src/Hermes.Abstractions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet {{proj_folder}} restore
    - name: Build
      run: dotnet {{proj_folder}} build --configuration Release --no-restore
